subcombs=combinesubs(["Anh" "Yi"],["Anh" "Yi"],2);
count=1;
for k=1:size(subcombs,1)
    path1="EOG"+subcombs(k,1)+"street";
    path2="EOG"+subcombs(k,2)+"street";
    type="street";
    if(subcombs(k,1)~=subcombs(k,2))
        for i=1:10
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"abspdf.mat");
            abshpdf1=y(1,:);
            absvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"deri1pdf.mat");
            deri1hpdf1=y(1,:);
            deri1vpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"deri2pdf.mat");
            deri2hpdf1=y(1,:);
            deri2vpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"fixdurationpdf.mat");
            fixdurationhpdf1=y(1,:);
            fixdurationvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"fixstartpdf.mat");
            fixstarthpdf1=y(1,:);
            fixstartvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"maxpdf.mat");
            maxhpdf1=y(1,:);
            maxvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"meanpdf.mat");
            meanhpdf1=y(1,:);
            meanvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"minpdf.mat");
            minhpdf1=y(1,:);
            minvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"sacamplitudepdf.mat");
            sacamplitudehpdf1=y(1,:);
            sacamplitudevpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"sacdurationpdf.mat");
            sacdurationhpdf1=y(1,:);
            sacdurationvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"sacstartpdf.mat");
            sacstarthpdf1=y(1,:);
            sacstartvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"blinkstartpdf.mat");
            blinkstartpdf1=y(1,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"blinkdurationpdf.mat");
            blinkdurationpdf1=y(1,:);
            for j=1:10
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"abspdf.mat");
                abshpdf2=y(1,:);
                absvpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"deri1pdf.mat");
                deri1hpdf2=y(1,:);
                deri1vpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"deri2pdf.mat");
                deri2hpdf2=y(1,:);
                deri2vpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"fixdurationpdf.mat");
                fixdurationhpdf2=y(1,:);
                fixdurationvpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"fixstartpdf.mat");
                fixstarthpdf2=y(1,:);
                fixstartvpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"maxpdf.mat");
                maxhpdf2=y(1,:);
                maxvpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"meanpdf.mat");
                meanhpdf2=y(1,:);
                meanvpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"minpdf.mat");
                minhpdf2=y(1,:);
                minvpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"sacamplitudepdf.mat");
                sacamplitudehpdf2=y(1,:);
                sacamplitudevpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"sacdurationpdf.mat");
                sacdurationhpdf2=y(1,:);
                sacdurationvpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"sacstartpdf.mat");
                sacstarthpdf2=y(1,:);
                sacstartvpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"blinkstartpdf.mat");
                blinkstartpdf2=y(1,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"blinkdurationpdf.mat");
                blinkdurationpdf2=y(1,:);
                [~,cm_P,~] = cmtest2(abshpdf1,abshpdf2);
                EOGstreetwholeset(count,1)=cm_P;
                [~,cm_P,~] = cmtest2(absvpdf1,absvpdf2);
                EOGstreetwholeset(count,2)=cm_P;
                [~,cm_P,~] = cmtest2(deri1hpdf1,deri1hpdf2);
                EOGstreetwholeset(count,3)=cm_P;
                [~,cm_P,~] = cmtest2(deri1vpdf1,deri1vpdf2);
                EOGstreetwholeset(count,4)=cm_P;
                [~,cm_P,~] = cmtest2(deri2hpdf1,deri2hpdf2);
                EOGstreetwholeset(count,5)=cm_P;
                [~,cm_P,~] = cmtest2(deri2vpdf1,deri2vpdf2);
                EOGstreetwholeset(count,6)=cm_P;
                [~,cm_P,~] = cmtest2(fixdurationhpdf1,fixdurationhpdf2);
                EOGstreetwholeset(count,7)=cm_P;
                [~,cm_P,~] = cmtest2(fixdurationvpdf1,fixdurationvpdf2);
                EOGstreetwholeset(count,8)=cm_P;
                [~,cm_P,~] = cmtest2(fixstarthpdf1,fixstarthpdf2);
                EOGstreetwholeset(count,9)=cm_P;
                [~,cm_P,~] = cmtest2(fixstartvpdf1,fixstartvpdf2);
                EOGstreetwholeset(count,10)=cm_P;
                [~,cm_P,~] = cmtest2(maxhpdf1,maxhpdf2);
                EOGstreetwholeset(count,11)=cm_P;
                [~,cm_P,~] = cmtest2(maxvpdf1,maxvpdf2);
                EOGstreetwholeset(count,12)=cm_P;
                [~,cm_P,~] = cmtest2(meanhpdf1,meanhpdf2);
                EOGstreetwholeset(count,13)=cm_P;
                [~,cm_P,~] = cmtest2(meanvpdf1,meanvpdf2);
                EOGstreetwholeset(count,14)=cm_P;
                [~,cm_P,~] = cmtest2(minhpdf1,minhpdf2);
                EOGstreetwholeset(count,15)=cm_P;
                [~,cm_P,~] = cmtest2(minvpdf1,minvpdf2);
                EOGstreetwholeset(count,16)=cm_P;
                [~,cm_P,~] = cmtest2(sacamplitudehpdf1,sacamplitudehpdf2);
                EOGstreetwholeset(count,17)=cm_P;
                [~,cm_P,~] = cmtest2(sacamplitudevpdf1,sacamplitudevpdf2);
                EOGstreetwholeset(count,18)=cm_P;
                [~,cm_P,~] = cmtest2(sacdurationhpdf1,sacdurationhpdf2);
                EOGstreetwholeset(count,19)=cm_P;
                [~,cm_P,~] = cmtest2(sacdurationvpdf1,sacdurationvpdf2);
                EOGstreetwholeset(count,20)=cm_P;
                [~,cm_P,~] = cmtest2(sacstarthpdf1,sacstarthpdf2);
                EOGstreetwholeset(count,21)=cm_P;
                [~,cm_P,~] = cmtest2(sacstartvpdf1,sacstartvpdf2);
                EOGstreetwholeset(count,22)=cm_P;
                [~,cm_P,~] = cmtest2(blinkstartpdf1,blinkstartpdf2);
                EOGstreetwholeset(count,23)=cm_P;
                [~,cm_P,~] = cmtest2(blinkdurationpdf1,blinkdurationpdf2);
                EOGstreetwholeset(count,24)=cm_P;

                EOGstreetwholeset(count,25)=(subcombs(k,1)~=subcombs(k,2));
                count=count+1;
            end
        end
    else
        for i=1:10
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"abspdf.mat");
            abshpdf1=y(1,:);
            absvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"deri1pdf.mat");
            deri1hpdf1=y(1,:);
            deri1vpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"deri2pdf.mat");
            deri2hpdf1=y(1,:);
            deri2vpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"fixdurationpdf.mat");
            fixdurationhpdf1=y(1,:);
            fixdurationvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"fixstartpdf.mat");
            fixstarthpdf1=y(1,:);
            fixstartvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"maxpdf.mat");
            maxhpdf1=y(1,:);
            maxvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"meanpdf.mat");
            meanhpdf1=y(1,:);
            meanvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"minpdf.mat");
            minhpdf1=y(1,:);
            minvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"sacamplitudepdf.mat");
            sacamplitudehpdf1=y(1,:);
            sacamplitudevpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"sacdurationpdf.mat");
            sacdurationhpdf1=y(1,:);
            sacdurationvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"sacstartpdf.mat");
            sacstarthpdf1=y(1,:);
            sacstartvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"blinkstartpdf.mat");
            blinkstartpdf1=y(1,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"blinkdurationpdf.mat");
            blinkdurationpdf1=y(1,:);
            for j=(i+1):10
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"abspdf.mat");
                abshpdf2=y(1,:);
                absvpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"deri1pdf.mat");
                deri1hpdf2=y(1,:);
                deri1vpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"deri2pdf.mat");
                deri2hpdf2=y(1,:);
                deri2vpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"fixdurationpdf.mat");
                fixdurationhpdf2=y(1,:);
                fixdurationvpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"fixstartpdf.mat");
                fixstarthpdf2=y(1,:);
                fixstartvpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"maxpdf.mat");
                maxhpdf2=y(1,:);
                maxvpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"meanpdf.mat");
                meanhpdf2=y(1,:);
                meanvpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"minpdf.mat");
                minhpdf2=y(1,:);
                minvpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"sacamplitudepdf.mat");
                sacamplitudehpdf2=y(1,:);
                sacamplitudevpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"sacdurationpdf.mat");
                sacdurationhpdf2=y(1,:);
                sacdurationvpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"sacstartpdf.mat");
                sacstarthpdf2=y(1,:);
                sacstartvpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"blinkstartpdf.mat");
                blinkstartpdf2=y(1,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"blinkdurationpdf.mat");
                blinkdurationpdf2=y(1,:);
                [~,cm_P,~] = cmtest2(abshpdf1,abshpdf2);
                EOGstreetwholeset(count,1)=cm_P;
                [~,cm_P,~] = cmtest2(absvpdf1,absvpdf2);
                EOGstreetwholeset(count,2)=cm_P;
                [~,cm_P,~] = cmtest2(deri1hpdf1,deri1hpdf2);
                EOGstreetwholeset(count,3)=cm_P;
                [~,cm_P,~] = cmtest2(deri1vpdf1,deri1vpdf2);
                EOGstreetwholeset(count,4)=cm_P;
                [~,cm_P,~] = cmtest2(deri2hpdf1,deri2hpdf2);
                EOGstreetwholeset(count,5)=cm_P;
                [~,cm_P,~] = cmtest2(deri2vpdf1,deri2vpdf2);
                EOGstreetwholeset(count,6)=cm_P;
                [~,cm_P,~] = cmtest2(fixdurationhpdf1,fixdurationhpdf2);
                EOGstreetwholeset(count,7)=cm_P;
                [~,cm_P,~] = cmtest2(fixdurationvpdf1,fixdurationvpdf2);
                EOGstreetwholeset(count,8)=cm_P;
                [~,cm_P,~] = cmtest2(fixstarthpdf1,fixstarthpdf2);
                EOGstreetwholeset(count,9)=cm_P;
                [~,cm_P,~] = cmtest2(fixstartvpdf1,fixstartvpdf2);
                EOGstreetwholeset(count,10)=cm_P;
                [~,cm_P,~] = cmtest2(maxhpdf1,maxhpdf2);
                EOGstreetwholeset(count,11)=cm_P;
                [~,cm_P,~] = cmtest2(maxvpdf1,maxvpdf2);
                EOGstreetwholeset(count,12)=cm_P;
                [~,cm_P,~] = cmtest2(meanhpdf1,meanhpdf2);
                EOGstreetwholeset(count,13)=cm_P;
                [~,cm_P,~] = cmtest2(meanvpdf1,meanvpdf2);
                EOGstreetwholeset(count,14)=cm_P;
                [~,cm_P,~] = cmtest2(minhpdf1,minhpdf2);
                EOGstreetwholeset(count,15)=cm_P;
                [~,cm_P,~] = cmtest2(minvpdf1,minvpdf2);
                EOGstreetwholeset(count,16)=cm_P;
                [~,cm_P,~] = cmtest2(sacamplitudehpdf1,sacamplitudehpdf2);
                EOGstreetwholeset(count,17)=cm_P;
                [~,cm_P,~] = cmtest2(sacamplitudevpdf1,sacamplitudevpdf2);
                EOGstreetwholeset(count,18)=cm_P;
                [~,cm_P,~] = cmtest2(sacdurationhpdf1,sacdurationhpdf2);
                EOGstreetwholeset(count,19)=cm_P;
                [~,cm_P,~] = cmtest2(sacdurationvpdf1,sacdurationvpdf2);
                EOGstreetwholeset(count,20)=cm_P;
                [~,cm_P,~] = cmtest2(sacstarthpdf1,sacstarthpdf2);
                EOGstreetwholeset(count,21)=cm_P;
                [~,cm_P,~] = cmtest2(sacstartvpdf1,sacstartvpdf2);
                EOGstreetwholeset(count,22)=cm_P;
                [~,cm_P,~] = cmtest2(blinkstartpdf1,blinkstartpdf2);
                EOGstreetwholeset(count,23)=cm_P;
                [~,cm_P,~] = cmtest2(blinkdurationpdf1,blinkdurationpdf2);
                EOGstreetwholeset(count,24)=cm_P;

                EOGstreetwholeset(count,25)=(subcombs(k,1)~=subcombs(k,2));
                count=count+1;
            end
        end
    end
    save("EOG"+type+"wholeset.mat",'EOGstreetwholeset');
end
