close all; clear;
subnum=32;
subcombs=combinesubs(["33" "34" "35" "36" "37" "38" "39" "40" "41" "42" "43" "44" "45" "46" "47" "48" "49" "50" "51" "52" "53" "54" "55" "56" "57" "58" "59" "60" "61" "62" "63" "64"],...
    ["33" "34" "35" "36" "37" "38" "39" "40" "41" "42" "43" "44" "45" "46" "47" "48" "49" "50" "51" "52" "53" "54" "55" "56" "57" "58" "59" "60" "61" "62" "63" "64"],subnum);
count=1;
datasize=(subnum*10)*(subnum*10-1)/2;
EOGfixtestset=zeros(datasize,47);
time="3s";
for k=1:size(subcombs,1)
    path1=subcombs(k,1)+"\EOG"+subcombs(k,1)+"fix";
    path2=subcombs(k,2)+"\EOG"+subcombs(k,2)+"fix";
    type="fix";
    if(subcombs(k,1)~=subcombs(k,2))
        for i=1:10
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"abspdf"+time+".mat");
            abshpdf1=y(1,:);
            absvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"deri1pdf"+time+".mat");
            deri1hpdf1=y(1,:);
            deri1vpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"deri2pdf"+time+".mat");
            deri2hpdf1=y(1,:);
            deri2vpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"fixdurationpdf"+time+".mat");
            fixdurationhpdf1=y(1,:);
            fixdurationvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"fixstartpdf"+time+".mat");
            fixstarthpdf1=y(1,:);
            fixstartvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"fixcentroidpdf"+time+".mat");
            fixcentroidhpdf1=y(1,:);
            fixcentroidvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"maxpdf"+time+".mat");
            maxhpdf1=y(1,:);
            maxvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"meanpdf"+time+".mat");
            meanhpdf1=y(1,:);
            meanvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"minpdf"+time+".mat");
            minhpdf1=y(1,:);
            minvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"sacamplitudepdf"+time+".mat");
            sacamplitudehpdf1=y(1,:);
            sacamplitudevpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"sacdurationpdf"+time+".mat");
            sacdurationhpdf1=y(1,:);
            sacdurationvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"sacstartpdf"+time+".mat");
            sacstarthpdf1=y(1,:);
            sacstartvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"blinkstartpdf"+time+".mat");
            blinkstartpdf1=y(1,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"blinkdurationpdf"+time+".mat");
            blinkdurationpdf1=y(1,:);
            
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"maxdistancepdf"+time+".mat");
            maxdistancehpdf1=y(1,:);
            maxdistancevpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"mindistancepdf"+time+".mat");
            mindistancehpdf1=y(1,:);
            mindistancevpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"slopeoppdf"+time+".mat");
            slopeophpdf1=y(1,:);
            slopeopvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"slopeonpdf"+time+".mat");
            slopeonhpdf1=y(1,:);
            slopeonvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"slopefppdf"+time+".mat");
            slopefphpdf1=y(1,:);
            slopefpvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"slopefnpdf"+time+".mat");
            slopefnhpdf1=y(1,:);
            slopefnvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"maxderipdf"+time+".mat");
            maxderihpdf1=y(1,:);
            maxderivpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"minderipdf"+time+".mat");
            minderihpdf1=y(1,:);
            minderivpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"maxderidistancepdf"+time+".mat");
            maxderidistancehpdf1=y(1,:);
            maxderidistancevpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"minderidistancepdf"+time+".mat");
            minderidistancehpdf1=y(1,:);
            minderidistancevpdf1=y(3,:);
            for j=1:10
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"abspdf"+time+".mat");
                abshpdf2=y(1,:);
                absvpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"deri1pdf"+time+".mat");
                deri1hpdf2=y(1,:);
                deri1vpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"deri2pdf"+time+".mat");
                deri2hpdf2=y(1,:);
                deri2vpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"fixdurationpdf"+time+".mat");
                fixdurationhpdf2=y(1,:);
                fixdurationvpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"fixstartpdf"+time+".mat");
                fixstarthpdf2=y(1,:);
                fixstartvpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"fixcentroidpdf"+time+".mat");
                fixcentroidhpdf2=y(1,:);
                fixcentroidvpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"maxpdf"+time+".mat");
                maxhpdf2=y(1,:);
                maxvpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"meanpdf"+time+".mat");
                meanhpdf2=y(1,:);
                meanvpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"minpdf"+time+".mat");
                minhpdf2=y(1,:);
                minvpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"sacamplitudepdf"+time+".mat");
                sacamplitudehpdf2=y(1,:);
                sacamplitudevpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"sacdurationpdf"+time+".mat");
                sacdurationhpdf2=y(1,:);
                sacdurationvpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"sacstartpdf"+time+".mat");
                sacstarthpdf2=y(1,:);
                sacstartvpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"blinkstartpdf"+time+".mat");
                blinkstartpdf2=y(1,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"blinkdurationpdf"+time+".mat");
                blinkdurationpdf2=y(1,:);
                
                load(".\"+path2+i+"\EOG"+subcombs(k,2)+type+i+"maxdistancepdf"+time+".mat");
                maxdistancehpdf2=y(1,:);
                maxdistancevpdf2=y(3,:);
                load(".\"+path2+i+"\EOG"+subcombs(k,2)+type+i+"mindistancepdf"+time+".mat");
                mindistancehpdf2=y(1,:);
                mindistancevpdf2=y(3,:);
                load(".\"+path2+i+"\EOG"+subcombs(k,2)+type+i+"slopeoppdf"+time+".mat");
                slopeophpdf2=y(1,:);
                slopeopvpdf2=y(3,:);
                load(".\"+path2+i+"\EOG"+subcombs(k,2)+type+i+"slopeonpdf"+time+".mat");
                slopeonhpdf2=y(1,:);
                slopeonvpdf2=y(3,:);
                load(".\"+path2+i+"\EOG"+subcombs(k,2)+type+i+"slopefppdf"+time+".mat");
                slopefphpdf2=y(1,:);
                slopefpvpdf2=y(3,:);
                load(".\"+path2+i+"\EOG"+subcombs(k,2)+type+i+"slopefnpdf"+time+".mat");
                slopefnhpdf2=y(1,:);
                slopefnvpdf2=y(3,:);
                load(".\"+path2+i+"\EOG"+subcombs(k,2)+type+i+"maxderipdf"+time+".mat");
                maxderihpdf2=y(1,:);
                maxderivpdf2=y(3,:);
                load(".\"+path2+i+"\EOG"+subcombs(k,2)+type+i+"minderipdf"+time+".mat");
                minderihpdf2=y(1,:);
                minderivpdf2=y(3,:);
                load(".\"+path2+i+"\EOG"+subcombs(k,2)+type+i+"maxderidistancepdf"+time+".mat");
                maxderidistancehpdf2=y(1,:);
                maxderidistancevpdf2=y(3,:);
                load(".\"+path2+i+"\EOG"+subcombs(k,2)+type+i+"minderidistancepdf"+time+".mat");
                minderidistancehpdf2=y(1,:);
                minderidistancevpdf2=y(3,:);
                [~,p] = ttest2(abshpdf1,abshpdf2);
                EOGfixtestset(count,1)=p;
                [~,p] = ttest2(absvpdf1,absvpdf2);
                EOGfixtestset(count,2)=p;
                [~,p] = ttest2(deri1hpdf1,deri1hpdf2);
                EOGfixtestset(count,3)=p;
                [~,p] = ttest2(deri1vpdf1,deri1vpdf2);
                EOGfixtestset(count,4)=p;
                [~,p] = ttest2(deri2hpdf1,deri2hpdf2);
                EOGfixtestset(count,5)=p;
                [~,p] = ttest2(deri2vpdf1,deri2vpdf2);
                EOGfixtestset(count,6)=p;
                [~,p] = ttest2(fixdurationhpdf1,fixdurationhpdf2);
                EOGfixtestset(count,7)=p;
                [~,p] = ttest2(fixdurationvpdf1,fixdurationvpdf2);
                EOGfixtestset(count,8)=p;
                [~,p] = ttest2(fixstarthpdf1,fixstarthpdf2);
                EOGfixtestset(count,9)=p;
                [~,p] = ttest2(fixstartvpdf1,fixstartvpdf2);
                EOGfixtestset(count,10)=p;
                [~,p] = ttest2(maxhpdf1,maxhpdf2);
                EOGfixtestset(count,11)=p;
                [~,p] = ttest2(maxvpdf1,maxvpdf2);
                EOGfixtestset(count,12)=p;
                [~,p] = ttest2(meanhpdf1,meanhpdf2);
                EOGfixtestset(count,13)=p;
                [~,p] = ttest2(meanvpdf1,meanvpdf2);
                EOGfixtestset(count,14)=p;
                [~,p] = ttest2(minhpdf1,minhpdf2);
                EOGfixtestset(count,15)=p;
                [~,p] = ttest2(minvpdf1,minvpdf2);
                EOGfixtestset(count,16)=p;
                [~,p] = ttest2(sacamplitudehpdf1,sacamplitudehpdf2);
                EOGfixtestset(count,17)=p;
                [~,p] = ttest2(sacamplitudevpdf1,sacamplitudevpdf2);
                EOGfixtestset(count,18)=p;
                [~,p] = ttest2(sacdurationhpdf1,sacdurationhpdf2);
                EOGfixtestset(count,19)=p;
                [~,p] = ttest2(sacdurationvpdf1,sacdurationvpdf2);
                EOGfixtestset(count,20)=p;
                [~,p] = ttest2(sacstarthpdf1,sacstarthpdf2);
                EOGfixtestset(count,21)=p;
                [~,p] = ttest2(sacstartvpdf1,sacstartvpdf2);
                EOGfixtestset(count,22)=p;
                [~,p] = ttest2(blinkstartpdf1,blinkstartpdf2);
                EOGfixtestset(count,23)=p;
                [~,p] = ttest2(blinkdurationpdf1,blinkdurationpdf2);
                EOGfixtestset(count,24)=p;
                [~,p] = ttest2(fixcentroidhpdf1,fixcentroidhpdf2);
                EOGfixtestset(count,25)=p;
                [~,p] = ttest2(fixcentroidvpdf1,fixcentroidvpdf2);
                EOGfixtestset(count,26)=p;
                
                [~,p] = ttest2(maxdistancehpdf1,maxdistancehpdf2);
                EOGfixtestset(count,27)=p;
                [~,p] = ttest2(maxdistancevpdf1,maxdistancevpdf2);
                EOGfixtestset(count,28)=p;
                [~,p] = ttest2(mindistancehpdf1,mindistancehpdf2);
                EOGfixtestset(count,29)=p;
                [~,p] = ttest2(mindistancevpdf1,mindistancevpdf2);
                EOGfixtestset(count,30)=p;
                [~,p] = ttest2(slopeophpdf1,slopeophpdf2);
                EOGfixtestset(count,31)=p;
                [~,p] = ttest2(slopeopvpdf1,slopeopvpdf2);
                EOGfixtestset(count,32)=p;
                [~,p] = ttest2(slopefphpdf1,slopefphpdf2);
                EOGfixtestset(count,33)=p;
                [~,p] = ttest2(slopefpvpdf1,slopefpvpdf2);
                EOGfixtestset(count,34)=p;
                [~,p] = ttest2(slopeonhpdf1,slopeonhpdf2);
                EOGfixtestset(count,35)=p;
                [~,p] = ttest2(slopeonvpdf1,slopeonvpdf2);
                EOGfixtestset(count,36)=p;
                [~,p] = ttest2(slopefnhpdf1,slopefnhpdf2);
                EOGfixtestset(count,37)=p;
                [~,p] = ttest2(slopefnvpdf1,slopefnvpdf2);
                EOGfixtestset(count,38)=p;
                [~,p] = ttest2(maxderihpdf1,maxderihpdf2);
                EOGfixtestset(count,39)=p;
                [~,p] = ttest2(maxderivpdf1,maxderivpdf2);
                EOGfixtestset(count,40)=p;
                [~,p] = ttest2(minderihpdf1,minderihpdf2);
                EOGfixtestset(count,41)=p;
                [~,p] = ttest2(minderivpdf1,minderivpdf2);
                EOGfixtestset(count,42)=p;
                [~,p] = ttest2(maxderidistancehpdf1,maxderidistancehpdf2);
                EOGfixtestset(count,43)=p;
                [~,p] = ttest2(maxderidistancevpdf1,maxderidistancevpdf2);
                EOGfixtestset(count,44)=p;
                [~,p] = ttest2(minderidistancehpdf1,minderidistancehpdf2);
                EOGfixtestset(count,45)=p;
                [~,p] = ttest2(minderidistancevpdf1,minderidistancevpdf2);
                EOGfixtestset(count,46)=p;
                
                EOGfixtestset(count,47)=(subcombs(k,1)~=subcombs(k,2));
                count=count+1;
            end
        end
    else
        for i=1:10
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"abspdf"+time+".mat");
            abshpdf1=y(1,:);
            absvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"deri1pdf"+time+".mat");
            deri1hpdf1=y(1,:);
            deri1vpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"deri2pdf"+time+".mat");
            deri2hpdf1=y(1,:);
            deri2vpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"fixdurationpdf"+time+".mat");
            fixdurationhpdf1=y(1,:);
            fixdurationvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"fixstartpdf"+time+".mat");
            fixstarthpdf1=y(1,:);
            fixstartvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"fixcentroidpdf"+time+".mat");
            fixcentroidhpdf1=y(1,:);
            fixcentroidvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"maxpdf"+time+".mat");
            maxhpdf1=y(1,:);
            maxvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"meanpdf"+time+".mat");
            meanhpdf1=y(1,:);
            meanvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"minpdf"+time+".mat");
            minhpdf1=y(1,:);
            minvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"sacamplitudepdf"+time+".mat");
            sacamplitudehpdf1=y(1,:);
            sacamplitudevpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"sacdurationpdf"+time+".mat");
            sacdurationhpdf1=y(1,:);
            sacdurationvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"sacstartpdf"+time+".mat");
            sacstarthpdf1=y(1,:);
            sacstartvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"blinkstartpdf"+time+".mat");
            blinkstartpdf1=y(1,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"blinkdurationpdf"+time+".mat");
            blinkdurationpdf1=y(1,:);
            
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"maxdistancepdf"+time+".mat");
            maxdistancehpdf1=y(1,:);
            maxdistancevpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"mindistancepdf"+time+".mat");
            mindistancehpdf1=y(1,:);
            mindistancevpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"slopeoppdf"+time+".mat");
            slopeophpdf1=y(1,:);
            slopeopvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"slopeonpdf"+time+".mat");
            slopeonhpdf1=y(1,:);
            slopeonvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"slopefppdf"+time+".mat");
            slopefphpdf1=y(1,:);
            slopefpvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"slopefnpdf"+time+".mat");
            slopefnhpdf1=y(1,:);
            slopefnvpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"maxderipdf"+time+".mat");
            maxderihpdf1=y(1,:);
            maxderivpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"minderipdf"+time+".mat");
            minderihpdf1=y(1,:);
            minderivpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"maxderidistancepdf"+time+".mat");
            maxderidistancehpdf1=y(1,:);
            maxderidistancevpdf1=y(3,:);
            load(".\"+path1+i+"\EOG"+subcombs(k,1)+type+i+"minderidistancepdf"+time+".mat");
            minderidistancehpdf1=y(1,:);
            minderidistancevpdf1=y(3,:);
            for j=(i+1):10
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"abspdf"+time+".mat");
                abshpdf2=y(1,:);
                absvpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"deri1pdf"+time+".mat");
                deri1hpdf2=y(1,:);
                deri1vpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"deri2pdf"+time+".mat");
                deri2hpdf2=y(1,:);
                deri2vpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"fixdurationpdf"+time+".mat");
                fixdurationhpdf2=y(1,:);
                fixdurationvpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"fixstartpdf"+time+".mat");
                fixstarthpdf2=y(1,:);
                fixstartvpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"fixcentroidpdf"+time+".mat");
                fixcentroidhpdf2=y(1,:);
                fixcentroidvpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"maxpdf"+time+".mat");
                maxhpdf2=y(1,:);
                maxvpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"meanpdf"+time+".mat");
                meanhpdf2=y(1,:);
                meanvpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"minpdf"+time+".mat");
                minhpdf2=y(1,:);
                minvpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"sacamplitudepdf"+time+".mat");
                sacamplitudehpdf2=y(1,:);
                sacamplitudevpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"sacdurationpdf"+time+".mat");
                sacdurationhpdf2=y(1,:);
                sacdurationvpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"sacstartpdf"+time+".mat");
                sacstarthpdf2=y(1,:);
                sacstartvpdf2=y(3,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"blinkstartpdf"+time+".mat");
                blinkstartpdf2=y(1,:);
                load(".\"+path2+j+"\EOG"+subcombs(k,2)+type+j+"blinkdurationpdf"+time+".mat");
                blinkdurationpdf2=y(1,:);
                
                load(".\"+path2+i+"\EOG"+subcombs(k,2)+type+i+"maxdistancepdf"+time+".mat");
                maxdistancehpdf2=y(1,:);
                maxdistancevpdf2=y(3,:);
                load(".\"+path2+i+"\EOG"+subcombs(k,2)+type+i+"mindistancepdf"+time+".mat");
                mindistancehpdf2=y(1,:);
                mindistancevpdf2=y(3,:);
                load(".\"+path2+i+"\EOG"+subcombs(k,2)+type+i+"slopeoppdf"+time+".mat");
                slopeophpdf2=y(1,:);
                slopeopvpdf2=y(3,:);
                load(".\"+path2+i+"\EOG"+subcombs(k,2)+type+i+"slopeonpdf"+time+".mat");
                slopeonhpdf2=y(1,:);
                slopeonvpdf2=y(3,:);
                load(".\"+path2+i+"\EOG"+subcombs(k,2)+type+i+"slopefppdf"+time+".mat");
                slopefphpdf2=y(1,:);
                slopefpvpdf2=y(3,:);
                load(".\"+path2+i+"\EOG"+subcombs(k,2)+type+i+"slopefnpdf"+time+".mat");
                slopefnhpdf2=y(1,:);
                slopefnvpdf2=y(3,:);
                load(".\"+path2+i+"\EOG"+subcombs(k,2)+type+i+"maxderipdf"+time+".mat");
                maxderihpdf2=y(1,:);
                maxderivpdf2=y(3,:);
                load(".\"+path2+i+"\EOG"+subcombs(k,2)+type+i+"minderipdf"+time+".mat");
                minderihpdf2=y(1,:);
                minderivpdf2=y(3,:);
                load(".\"+path2+i+"\EOG"+subcombs(k,2)+type+i+"maxderidistancepdf"+time+".mat");
                maxderidistancehpdf2=y(1,:);
                maxderidistancevpdf2=y(3,:);
                load(".\"+path2+i+"\EOG"+subcombs(k,2)+type+i+"minderidistancepdf"+time+".mat");
                minderidistancehpdf2=y(1,:);
                minderidistancevpdf2=y(3,:);
                
                [~,p] = ttest2(abshpdf1,abshpdf2);
                EOGfixtestset(count,1)=p;
                [~,p] = ttest2(absvpdf1,absvpdf2);
                EOGfixtestset(count,2)=p;
                [~,p] = ttest2(deri1hpdf1,deri1hpdf2);
                EOGfixtestset(count,3)=p;
                [~,p] = ttest2(deri1vpdf1,deri1vpdf2);
                EOGfixtestset(count,4)=p;
                [~,p] = ttest2(deri2hpdf1,deri2hpdf2);
                EOGfixtestset(count,5)=p;
                [~,p] = ttest2(deri2vpdf1,deri2vpdf2);
                EOGfixtestset(count,6)=p;
                [~,p] = ttest2(fixdurationhpdf1,fixdurationhpdf2);
                EOGfixtestset(count,7)=p;
                [~,p] = ttest2(fixdurationvpdf1,fixdurationvpdf2);
                EOGfixtestset(count,8)=p;
                [~,p] = ttest2(fixstarthpdf1,fixstarthpdf2);
                EOGfixtestset(count,9)=p;
                [~,p] = ttest2(fixstartvpdf1,fixstartvpdf2);
                EOGfixtestset(count,10)=p;
                [~,p] = ttest2(maxhpdf1,maxhpdf2);
                EOGfixtestset(count,11)=p;
                [~,p] = ttest2(maxvpdf1,maxvpdf2);
                EOGfixtestset(count,12)=p;
                [~,p] = ttest2(meanhpdf1,meanhpdf2);
                EOGfixtestset(count,13)=p;
                [~,p] = ttest2(meanvpdf1,meanvpdf2);
                EOGfixtestset(count,14)=p;
                [~,p] = ttest2(minhpdf1,minhpdf2);
                EOGfixtestset(count,15)=p;
                [~,p] = ttest2(minvpdf1,minvpdf2);
                EOGfixtestset(count,16)=p;
                [~,p] = ttest2(sacamplitudehpdf1,sacamplitudehpdf2);
                EOGfixtestset(count,17)=p;
                [~,p] = ttest2(sacamplitudevpdf1,sacamplitudevpdf2);
                EOGfixtestset(count,18)=p;
                [~,p] = ttest2(sacdurationhpdf1,sacdurationhpdf2);
                EOGfixtestset(count,19)=p;
                [~,p] = ttest2(sacdurationvpdf1,sacdurationvpdf2);
                EOGfixtestset(count,20)=p;
                [~,p] = ttest2(sacstarthpdf1,sacstarthpdf2);
                EOGfixtestset(count,21)=p;
                [~,p] = ttest2(sacstartvpdf1,sacstartvpdf2);
                EOGfixtestset(count,22)=p;
                [~,p] = ttest2(blinkstartpdf1,blinkstartpdf2);
                EOGfixtestset(count,23)=p;
                [~,p] = ttest2(blinkdurationpdf1,blinkdurationpdf2);
                EOGfixtestset(count,24)=p;
                [~,p] = ttest2(fixcentroidhpdf1,fixcentroidhpdf2);
                EOGfixtestset(count,25)=p;
                [~,p] = ttest2(fixcentroidvpdf1,fixcentroidvpdf2);
                EOGfixtestset(count,26)=p;
                
                [~,p] = ttest2(maxdistancehpdf1,maxdistancehpdf2);
                EOGfixtestset(count,27)=p;
                [~,p] = ttest2(maxdistancevpdf1,maxdistancevpdf2);
                EOGfixtestset(count,28)=p;
                [~,p] = ttest2(mindistancehpdf1,mindistancehpdf2);
                EOGfixtestset(count,29)=p;
                [~,p] = ttest2(mindistancevpdf1,mindistancevpdf2);
                EOGfixtestset(count,30)=p;
                [~,p] = ttest2(slopeophpdf1,slopeophpdf2);
                EOGfixtestset(count,31)=p;
                [~,p] = ttest2(slopeopvpdf1,slopeopvpdf2);
                EOGfixtestset(count,32)=p;
                [~,p] = ttest2(slopefphpdf1,slopefphpdf2);
                EOGfixtestset(count,33)=p;
                [~,p] = ttest2(slopefpvpdf1,slopefpvpdf2);
                EOGfixtestset(count,34)=p;
                [~,p] = ttest2(slopeonhpdf1,slopeonhpdf2);
                EOGfixtestset(count,35)=p;
                [~,p] = ttest2(slopeonvpdf1,slopeonvpdf2);
                EOGfixtestset(count,36)=p;
                [~,p] = ttest2(slopefnhpdf1,slopefnhpdf2);
                EOGfixtestset(count,37)=p;
                [~,p] = ttest2(slopefnvpdf1,slopefnvpdf2);
                EOGfixtestset(count,38)=p;
                [~,p] = ttest2(maxderihpdf1,maxderihpdf2);
                EOGfixtestset(count,39)=p;
                [~,p] = ttest2(maxderivpdf1,maxderivpdf2);
                EOGfixtestset(count,40)=p;
                [~,p] = ttest2(minderihpdf1,minderihpdf2);
                EOGfixtestset(count,41)=p;
                [~,p] = ttest2(minderivpdf1,minderivpdf2);
                EOGfixtestset(count,42)=p;
                [~,p] = ttest2(maxderidistancehpdf1,maxderidistancehpdf2);
                EOGfixtestset(count,43)=p;
                [~,p] = ttest2(maxderidistancevpdf1,maxderidistancevpdf2);
                EOGfixtestset(count,44)=p;
                [~,p] = ttest2(minderidistancehpdf1,minderidistancehpdf2);
                EOGfixtestset(count,45)=p;
                [~,p] = ttest2(minderidistancevpdf1,minderidistancevpdf2);
                EOGfixtestset(count,46)=p;

                EOGfixtestset(count,47)=(subcombs(k,1)~=subcombs(k,2));
                count=count+1;
            end
        end
    end
    save("EOG"+type+"testset"+time+".mat",'EOGfixtestset');
end
